# Generated by Django 4.0.1 on 2022-01-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewJoinerDetails',
            fields=[
                ('PSID', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('other_phone', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('dept_id', models.IntegerField()),
                ('email_address', models.EmailField(max_length=200, unique=True)),
                ('date_of_joining', models.DateTimeField()),
                ('work_location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'NewJoinerCandidateData',
                'managed': False,
            },
        ),
    ]
